<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="fb-root"></div>
<div class="fb-like-box" data-href="http://www.facebook.com/3aART" data-width="297" data-colorscheme="dark" data-show-faces="false" data-stream="false" data-header="false" style="padding-top:30px;"></div>
