<article class="grid_13 alpha">
	<section>
		<div class="grid_9 alpha">
			<div class="box">
				<p><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</strong> Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.</p>
				<p><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</strong> Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.</p>
			</div>
		</div>
		<div class="grid_4 omega">
			<img src="http://lorempixel.com/204/165/" title="Bild"><br/>
			<img src="http://lorempixel.com/204/165/" title="Bild">
		</div>

	</section>
	<div class="clear"></div>
	<section><h2>Leistungsbeschreibung</h2>

		<div class="grid_9 alpha">

			<div class="box">
				<p><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</strong> Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.</p>
				<p><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</strong> Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.</p>
			</div>
		</div>
		<div class="grid_4 omega">
			<img src="http://lorempixel.com/204/165/" title="Bild"><br/>
			<img src="http://lorempixel.com/204/165/" title="Bild">
		</div>
	</section>
	<div class="clear"></div>
</article>
<aside class="grid_6 prefix_1 omega">
	<div class="teaser">
		<img src="http://lorempixel.com/316/110/" title="Bild">

		<p>Wählen Sie aus Hunderten von Motiven und gestalten Sie Ihr eigenes Bild</p>

		<p class="calltoaction"><a href="/motive">zur Motivauswahl</a></p>
	</div>
	<hr class="teaser">
	<div class="teaser">
		<img src="http://lorempixel.com/316/110/" title="Bild">
		<p>Wählen Sie aus Hunderten von Motiven und gestalten Sie Ihr eigenes Bild</p>
		<p class="calltoaction"><a href="/motive">zur Motivauswahl</a></p>
	</div>
</aside>
<div class="clear"></div>