<div id="content-slider" class="slider grid_20 alpha omega">
    <img src="<?php echo $this->getSkinUrl('images/referenzen-slider.png'); ?>" title="Referenzen Slider" />
</div>
<div class="clear"></div>
<article class="grid_13 alpha">
	<section>
			<div class="box">
				<p><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</strong> Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.</p>
				<p><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</strong> Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes.</p>
			</div>
        <h2>Leasing Partner</h2>
            <ul class="iconlist">
	            <li><a href="#"><img src="http://lorempixel.com/120/80"></a></li>
	            <li><a href="#"><img src="http://lorempixel.com/120/80"></a></li>
	            <li><a href="#"><img src="http://lorempixel.com/120/80"></a></li>
	            <li><a href="#"><img src="http://lorempixel.com/120/80"></a></li>
	            <li class="last"><a href="#"><img src="http://lorempixel.com/120/80"></a></li>
            </ul>
	</section>
	<div class="clear"></div>
</article>
<aside class="grid_6 prefix_1 omega">
    <h3>Ansprechpartner</h3>
	<div class="ansprechpartner">
        <div class="grid_2 alpha">
	        <img src="http://lorempixel.com/94/121/people/9" title="Bild">
        </div>
        <div class="grid_4 omega">
	        <p><strong>Andrea Lease</strong><br>
		        Partner Manager</p>
            <p>Telefon: +49-89-555 000-112<br>
		        Email: <a href="mailto:leasing@3aart.de?subject=Leasinganfrage">leasing@3aart.de</a></p>

        </div>
        <div class="clear"></div>
		<p class="calltoaction"><a href="/motive">Leasing AGB</a></p>
	</div>
</aside>
<div class="clear"></div>