<ul class="mainnavigation">
    <li><a href="/" title="Home" id="link-home"><span>Home</span></a></li>
    <li><a href="/motive" title="Motive" id="link-motive"><span>Motive</span></a></li>
    <li><a href="/mein-motive" title="Mein Motiv" id="link-meinmotiv"><span>Motive</span></a></li>
    <li><a href="/produkt" title="Produkt" id="link-produkt"><span>Produkt</span></a></li>
    <li><a href="/zubehoer" title="Zubehör" id="link-zubehoer"><span>Zubehör</span></a></li>
    <li><a href="/leasing" title="Leasing" id="link-leasing" class="active  "><span>Leasing</span></a></li>
    <li><a href="/ueber-uns" title="Über uns" id="link-ueberuns"><span>Über uns</span></a></li>
    <li><a href="/service" title="Service" id="link-service"><span>Service</span></a></li>
    <li><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>" title="Login" id="link-login"><span>Login</span></a></li>
</ul>