<ul class="social-networks iconlist">
    <li><a href="#" title="Youtube"><img src="<?php echo $this->getSkinUrl( 'images/icons/youtube.png' ); ?>" title="3aART bei Youtube"></a></li>
    <li><a href="http://www.facebook.com/3aART" title="Facebook"><img src="<?php echo $this->getSkinUrl( 'images/icons/facebook.png' ); ?>" title="3aART bei Facebook"></a></li>
    <li style="position:relative"><?php echo $this->getChildHtml( 'footer.socialnetworks.facebook' ) ?></li>
</ul>
